[features]
seeds = false
skip-lint = false
[programs.localnet]
ticket_box_program = "9oaNngp1cLnRchZRqbA3ubz1mUx5kWv4TNkpNq41Vwqc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/d1xhaXHPD05-f90hSAL7sU4V16mP_usx"
# cluster = "localnet"
wallet = "/Users/khacvy/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-initialize.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-initialize-with-currency.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
